name: Continuous Deployment

on:
  pull_request:
    branches: main

jobs:
  test_pull_request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Login to DockerHub
      env: 
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 

    - name: Build Docker images
      run: docker compose -f docker-compose.yml build 

    - name: Push Docker images
      run: docker compose -f docker-compose.yml push 

    - name: copy files to target server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{secrets.EC2_INSTANCE_IP}}
        username: ec2-user
        key: ${{secrets.PASSWORD}}
        source: "docker-compose.yml"
        target: "."

    - name: Build and Start Docker Compose
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.EC2_INSTANCE_IP}}
        username: ec2-user
        key: ${{secrets.PASSWORD}}
        script: |
          docker-compose stop
          docker-compose rm -f
          docker-compose up -d


    
